import { Pressable, StyleSheet, Text, View } from "react-native";
import { formatLogListDate } from "../journal-format";
import { describeAverageOutcome, outcomeTrend, OutcomeTrendRange } from "../outcome-trends";
import { JournalCategory, JournalSnapshot, OutcomePhase } from "../journal-storage";

export function OutcomeTrendsView({ journal, category, range, phase, onRangeChange, onPhaseChange, onOpenEntry }: {
  journal: JournalSnapshot;
  category: JournalCategory | null;
  range: OutcomeTrendRange;
  phase: OutcomePhase;
  onRangeChange: (range: OutcomeTrendRange) => void;
  onPhaseChange: (phase: OutcomePhase) => void;
  onOpenEntry: (entryId: string) => void;
}) {
  const trend = category ? outcomeTrend(journal.entries, journal.outcomeCheckIns, category.id, phase, range) : null;
  const sources = trend ? trend.sourceEntryIds.map((id) => journal.entries.find((entry) => entry.id === id)).filter((entry): entry is NonNullable<typeof entry> => Boolean(entry)) : [];
  return <View style={styles.stack}>
    <View style={styles.rangeRow}>{([30, 90] as OutcomeTrendRange[]).map((nextRange) => <Pressable key={nextRange} accessibilityState={{ selected: range === nextRange }} onPress={() => onRangeChange(nextRange)} style={[styles.range, range === nextRange && styles.rangeSelected]}><Text style={[styles.rangeText, range === nextRange && styles.rangeTextSelected]}>Last {nextRange} days</Text></Pressable>)}</View>
    <View style={styles.phaseRow}>{(["immediate", "delayed"] as OutcomePhase[]).map((nextPhase) => <Pressable key={nextPhase} accessibilityState={{ selected: phase === nextPhase }} onPress={() => onPhaseChange(nextPhase)} style={[styles.phase, phase === nextPhase && styles.phaseSelected]}><Text style={[styles.phaseText, phase === nextPhase && styles.phaseTextSelected]}>{nextPhase === "immediate" ? "Right after" : "Later"}</Text></Pressable>)}</View>
    {!category ? <View style={styles.emptyCard}><Text style={styles.emptyTitle}>Choose a category</Text><Text style={styles.emptyText}>Select a category above to review its reported outcomes. Foresight does not label categories good or bad.</Text></View> : <OutcomeSummary category={category} trend={trend!} phase={phase} range={range} sources={sources} onOpenEntry={onOpenEntry} />}
  </View>;
}

function OutcomeSummary({ category, trend, phase, range, sources, onOpenEntry }: { category: JournalCategory; trend: ReturnType<typeof outcomeTrend>; phase: OutcomePhase; range: OutcomeTrendRange; sources: { id: string; body: string; eventAt: string }[]; onOpenEntry: (entryId: string) => void }) {
  const responseRate = trend.responseRate === null ? null : Math.round(trend.responseRate * 100);
  const phaseLabel = phase === "immediate" ? "right after" : "later";
  return <View style={styles.stack}><View style={styles.card}><Text style={styles.eyebrow}>Reported outcomes</Text><Text style={styles.cardTitle}>{category.name}</Text><Text style={styles.description}>{trend.logCount === 1 ? "1 log" : `${trend.logCount} logs`} in the last {range} days · {phaseLabel}</Text>{trend.scheduledCount === 0 ? <Text style={styles.emptyText}>No {phaseLabel} check-ins were scheduled for these logs yet.</Text> : <><View style={styles.stats}><Stat label="Reported" value={`${trend.responseCount}/${trend.scheduledCount}`} /><Stat label="Response rate" value={`${responseRate}%`} /><Stat label="Numeric" value={`${trend.numericCount}`} /></View><Text style={styles.detail}>{trend.notSureCount > 0 ? `${trend.notSureCount} marked not sure. ` : ""}{trend.skippedCount > 0 ? `${trend.skippedCount} skipped. ` : ""}{trend.pendingCount > 0 ? `${trend.pendingCount} still pending.` : ""}</Text><View style={styles.distribution}><Stat label="Better" value={`${trend.betterCount}`} /><Stat label="Same" value={`${trend.sameCount}`} /><Stat label="Worse" value={`${trend.worseCount}`} /></View>{trend.hasEnoughEvidence && trend.average !== null ? <Text style={styles.insight}>In {trend.numericCount} recorded {phaseLabel} check-ins for {category.name}, you reported feeling {describeAverageOutcome(trend.average)} on average.</Text> : <Text style={styles.caution}>Record at least 5 numeric responses before Foresight summarizes a pattern. Counts above are shown without making a conclusion.</Text>}</>}</View>{sources.length > 0 ? <View style={styles.card}><Text style={styles.eyebrow}>Source logs</Text><Text style={styles.cardTitle}>See the context</Text>{sources.map((entry) => <Pressable key={entry.id} accessibilityLabel={`Open source log from ${formatLogListDate(entry.eventAt)}`} onPress={() => onOpenEntry(entry.id)} style={styles.source}><View><Text style={styles.sourceDate}>{formatLogListDate(entry.eventAt)}</Text><Text numberOfLines={2} style={styles.sourceBody}>{entry.body}</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}</View> : null}</View>;
}

function Stat({ label, value }: { label: string; value: string }) {
  return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>;
}

const colors = { surface: "#FFFEFA", ink: "#20231F", muted: "#667067", line: "#D9DDD5", sageDark: "#34503F" };
const styles = StyleSheet.create({ stack: { gap: 14 }, rangeRow: { flexDirection: "row", gap: 8 }, range: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 100, borderWidth: 1, flex: 1, paddingVertical: 10 }, rangeSelected: { backgroundColor: colors.sageDark, borderColor: colors.sageDark }, rangeText: { color: colors.ink, fontSize: 14, fontWeight: "800" }, rangeTextSelected: { color: "#FFFFFF" }, phaseRow: { flexDirection: "row", gap: 8 }, phase: { alignItems: "center", borderBottomColor: colors.line, borderBottomWidth: 1, flex: 1, paddingVertical: 9 }, phaseSelected: { borderBottomColor: colors.sageDark, borderBottomWidth: 3 }, phaseText: { color: colors.muted, fontSize: 14, fontWeight: "800" }, phaseTextSelected: { color: colors.sageDark }, card: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 18, borderWidth: 1, gap: 12, padding: 20 }, eyebrow: { color: colors.sageDark, fontSize: 11, fontWeight: "800", letterSpacing: 1.35, textTransform: "uppercase" }, cardTitle: { color: colors.ink, fontFamily: "Georgia", fontSize: 25, letterSpacing: -0.45, lineHeight: 30 }, description: { color: colors.muted, fontSize: 13, lineHeight: 19 }, stats: { flexDirection: "row", gap: 8 }, stat: { backgroundColor: "#EDEFE9", borderRadius: 10, flex: 1, gap: 2, padding: 10 }, statValue: { color: colors.sageDark, fontSize: 18, fontWeight: "800" }, statLabel: { color: colors.muted, fontSize: 11, fontWeight: "700" }, detail: { color: colors.muted, fontSize: 12, lineHeight: 18 }, distribution: { borderTopColor: colors.line, borderTopWidth: 1, flexDirection: "row", gap: 8, paddingTop: 12 }, insight: { backgroundColor: "#E8EEE7", borderRadius: 11, color: colors.ink, fontSize: 14, lineHeight: 21, padding: 14 }, caution: { color: colors.muted, fontSize: 13, lineHeight: 19 }, emptyCard: { alignItems: "center", backgroundColor: "#EDEFE9", borderRadius: 18, gap: 8, minHeight: 160, justifyContent: "center", padding: 24 }, emptyTitle: { color: colors.ink, fontFamily: "Georgia", fontSize: 22 }, emptyText: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: "center" }, source: { alignItems: "center", borderTopColor: colors.line, borderTopWidth: 1, flexDirection: "row", justifyContent: "space-between", paddingTop: 12 }, sourceDate: { color: colors.sageDark, fontSize: 12, fontWeight: "800" }, sourceBody: { color: colors.ink, fontSize: 14, lineHeight: 20, marginTop: 3, maxWidth: 240 }, chevron: { color: colors.sageDark, fontSize: 24, fontWeight: "400" } });
